openapi: 3.0.0
info:
  title: API.Produto
  description: ''
  version: 1.0.0
  termsOfService: 'http://swagger.io/terms/'
servers:
  - url: 'http://127.0.0.1:8000/api/v1'
    description: Sandbox
paths:
  /product:
    get:
      tags:
        - Produtos
      summary: Retorna os produtos.
      responses:
      
        '200':
          description: Listagem dos produtos disponíveis.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/products"
    
        '405':
          description: Método não permitido.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
          
        '500':
          description: Erro interno do servidor (Internal Server Error).
          
          
          
components:

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      
  schemas:
  
    products:  
      type: array
      items:
        $ref: "#/components/schemas/product"
        
    product:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        price:
          type: number
          format: decimal
        product_category_id:
          type: integer
        status:
          type: boolean
        created_at:
          type: string
          format: data
        updated_at:
          type: string
          format: data
        additionals:
          $ref: "#/components/schemas/additionals"
          
        category:
          $ref: "#/components/schemas/category"
          
        images:
          $ref: "#/components/schemas/images"
          
    additionals:
      type: array
      items:
        $ref: "#/components/schemas/additional"
        
    additional:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        price: 
          type: number
          format: decimal
        product_additional_category_id:
          type: integer
        created_at:
          type: string
          format: data
        updated_at:
          type: string
          format: data
        pivot:
          type: object
          properties:
            product_id:
              type: integer
            product_additional_id:
              type: integer
           
    category:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        status:
          type: boolean   
        
    images:
      type: array
      items:
        $ref: "#/components/schemas/image"
        
    image:
      type: object
      properties:
        id:
          type: integer
        product_id:
          type: integer
        created_at:
          type: string
          format: data
        updated_at:
          type: string
          format: data
          
    error:
      type: object
      properties:
        error:
          type: object
          properties:
            description:
              type: string
            messages:
              type: array
              items:
                type: string
      
        
    
      
    
    
    
    
    
    
    
    
    
    
    
    
    
    
