openapi: 3.0.0
info:
  title: API.Produto
  description: ''
  version: 1.0.0
  termsOfService: 'http://swagger.io/terms/'
servers:
  - url: 'http://127.0.0.1:8000/api/v1'
    description: Sandbox


paths:

  /product:

    get:

      tags:
        - Product
      summary: Retorna os produtos.
      responses:

        '200':
          description: Listagem dos produtos disponíveis.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/products"

        '405':
          description: Método não permitido.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"

        '500':
          description: Erro interno do servidor (Internal Server Error).

    post:
      summary: Cadastrar produto.

      security:
        - bearerAuth: []

      tags:
        - Product
      responses:
        '201':
          description: Produto cadastrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/productStatus2x'

        '401':
          description: Não autorizado.

        '422':
          description: Entidade improcessável.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorMessage"

        '500':
          description: Erro interno do servidor (Internal Server Error).

      requestBody:
        $ref: '#/components/requestBodies/Product'

  /product/{productId}:
    parameters:
      - $ref: '#/components/parameters/productId'

    get:

      tags:
        - Product
      summary: Retorna produto pelo ID.
      responses:

        '200':
          description: Listagem dos produtos disponíveis.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/product"

        '404':
          description: Produto não encontrado.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorMessage"

        '405':
          description: Método não permitido.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"

        '500':
          description: Erro interno do servidor (Internal Server Error).

    put:

      summary: Editar produto.

      security:
        - bearerAuth: []

      tags:
        - Product
      responses:
        '200':
          description: Produto cadastrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/productStatus2x'

        '404':
          description: Produto não encontrado.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorMessage"

        '401':
          description: Não autorizado.

        '422':
          description: Entidade improcessável.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorMessage"


        '500':
          description: Erro interno do servidor (Internal Server Error).

      requestBody:
        $ref: '#/components/requestBodies/Product'

    patch:

      summary: Editar dados do produto.

      security:
        - bearerAuth: []

      tags:
        - Product
      responses:
        '200':
          description: Produto cadastrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/productStatus2x'

        '404':
          description: Produto não encontrado.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorMessage"

        '401':
          description: Não autorizado.

        '422':
          description: Entidade improcessável.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorMessage"


        '500':
          description: Erro interno do servidor (Internal Server Error).

      requestBody:
        $ref: '#/components/requestBodies/Product'

    delete:

      tags:
        - Product

      summary: Excluir produto.

      security:
        - bearerAuth: []

      responses:

        '200':
          description: ok.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorMessage"

        '404':
          description: Produto não encontrado.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorMessage"

        '405':
          description: Método não permitido.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"

        '500':
          description: Erro interno do servidor (Internal Server Error).

  /product/q/{name}:
    get:

      parameters:
        - $ref: '#/components/parameters/q'

      tags:
        - Product
      summary: Retorna produto pelo ID.
      responses:

        '200':
          description: Listagem dos produtos disponíveis.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/product"

        '404':
          description: Produto não encontrado.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorMessage"

        '405':
          description: Método não permitido.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"

        '500':
          description: Erro interno do servidor (Internal Server Error).

  /product/{productId}/additional:
    parameters:
      - $ref: '#/components/parameters/productId'

    post:
      summary: Inserir produto adicional em um produto.

      security:
        - bearerAuth: []

      tags:
        - Product
      responses:
        '201':
          description: Produto adicional cadastrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/productStatus2x'

        '401':
          description: Não autorizado.

        '422':
          description: Entidade improcessável.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorMessage"

        '500':
          description: Erro interno do servidor (Internal Server Error).

      requestBody:
        $ref: '#/components/requestBodies/ProductAdditional'

  /product/category:
    post:
      summary: Cadastrar categoria do produto.

      security:
        - bearerAuth: []

      tags:
        - Product Category
      responses:
        '201':
          description: Categoria cadastrada.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/productStatus2x'

        '401':
          description: Não autorizado.

        '422':
          description: Entidade improcessável.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorMessage"

        '500':
          description: Erro interno do servidor (Internal Server Error).

      requestBody:
        $ref: '#/components/requestBodies/Category'

    get:
      summary: Retornar todas as categorias do produto.

      security:
        - bearerAuth: []

      tags:
        - Product Category
      responses:
        '200':
          description: ok.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductCategory'

        '401':
          description: Não autorizado.

        '422':
          description: Entidade improcessável.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorMessage"

        '500':
          description: Erro interno do servidor (Internal Server Error).


components:

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  parameters:

    productId:
      name: productId
      in: path
      required: true
      description: ID do produto.
      schema:
        type: string

    q:
      name: name
      in: path
      required: true
      description: Nome.
      schema:
        type: string

  requestBodies:

    Product:
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: boolean
              name:
                type: string
              price:
                type: number
                format: decimal
              product_category_id:
                type: integer

    Category:
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: boolean
              name:
                type: string


    ProductAdditional:
      content:
        application/json:
          schema:
            type: object
            properties:
              additionalsId:
                type: array
                items:
                  type: integer


  schemas:

    products:
      type: array
      items:
        $ref: "#/components/schemas/product"

    product:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        price:
          type: number
          format: decimal
        product_category_id:
          type: integer
        status:
          type: boolean
        created_at:
          type: string
          format: data
        updated_at:
          type: string
          format: data
        additionals:
          $ref: "#/components/schemas/additionals"

        category:
          $ref: "#/components/schemas/category"

        images:
          $ref: "#/components/schemas/images"

    additionals:
      type: array
      items:
        $ref: "#/components/schemas/additional"

    additional:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        price:
          type: number
          format: decimal
        product_additional_category_id:
          type: integer
        created_at:
          type: string
          format: data
        updated_at:
          type: string
          format: data
        pivot:
          type: object
          properties:
            product_id:
              type: integer
            product_additional_id:
              type: integer

    category:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        status:
          type: boolean

    images:
      type: array
      items:
        $ref: "#/components/schemas/image"

    image:
      type: object
      properties:
        id:
          type: integer
        product_id:
          type: integer
        created_at:
          type: string
          format: data
        updated_at:
          type: string
          format: data

    productStatus2x:
      type: object
      properties:
        status:
          type: boolean
        name:
          type: string
        price:
          type: number
          format: decimal
        product_category_id:
          type: integer
        id:
          type: integer
        created_at:
          type: string
          format: data
        updated_at:
          type: string
          format: data

    ProductCategory:
      type: object
      properties:
        status:
          type: boolean
        name:
          type: string
        products:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
              price:
                type: number
                format: decimal
              product_category_id:
                type: integer
              status:
                type: boolean
              created_at:
                type: string
                format: data
              updated_at:
                type: string
                format: data

    error:
      type: object
      properties:
        error:
          type: object
          properties:
            description:
              type: string
            messages:
              type: array
              items:
                type: string

    errorMessage:
      type: object
      properties:
        message:
          type: string
        errors:
          type: string



















